language: node_js
cache: yarn
node_js:
  - node
  - "8"
install:
  - YARN_IGNORE_ENGINES=true yarn
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search